### PR TITLE
Add some footer links

### PR DESCRIPTION
**Pull request by lynnandtonic**
This PR adds the overview, FAQ, and Github links to the bottom of the page

image

### CODE REVIEW

**Comment by lynnandtonic** [comment]
@crcastle @lukekarrys One more quick PR here

**Comment by lukekarrys** [comment]
👍 lgtm!

**Comment by lynnandtonic** [comment]
@lukekarrys Thanks! Gonna merge. Does a deploy happen automatically?

**Comment by lukekarrys** [comment]
@lynnandtonic Yep! It should be deployed

**Comment by lynnandtonic** [comment]
@lukekarrys Thank youuuu

**Pull request merged**
